DROP TABLE IF EXISTS #db#.User//
CREATE TABLE #db#.User (
	`id` INT UNSIGNED auto_increment ,
	`role` INT UNSIGNED NOT NULL DEFAULT 0,
	`username` VARCHAR(1) NOT NULL DEFAULT "",
	`email` VARCHAR(100) NOT NULL DEFAULT "",
	`password` VARCHAR(32) NOT NULL DEFAULT "",
	`timezone` FLOAT NOT NULL DEFAULT 0.0,
	`active` INT UNSIGNED NOT NULL DEFAULT 0,
	`lastturntime` INT UNSIGNED NOT NULL DEFAULT 0,
	`datecreated` INT UNSIGNED NOT NULL DEFAULT 0,
	`datebanned` INT UNSIGNED NOT NULL DEFAULT 0,
	`reason` VARCHAR(1) NOT NULL DEFAULT "",
	`nation` INT UNSIGNED NOT NULL DEFAULT 0,
	`commander` INT UNSIGNED NOT NULL DEFAULT 0,
	`clicks` INT UNSIGNED NOT NULL DEFAULT 0,
	`food` INT UNSIGNED NOT NULL DEFAULT 50000,
	`steel` INT UNSIGNED NOT NULL DEFAULT 50000,
	`oil` INT UNSIGNED NOT NULL DEFAULT 50000,
	`exp` INT UNSIGNED NOT NULL DEFAULT 0,
	`gold` INT UNSIGNED NOT NULL DEFAULT 50000,
	`morale` INT UNSIGNED NOT NULL DEFAULT 5000,
	`rank` INT UNSIGNED NOT NULL DEFAULT 0,
	`civilains` INT UNSIGNED NOT NULL DEFAULT 50000,
	`airforce` INT UNSIGNED NOT NULL DEFAULT 0,
	`army` INT UNSIGNED NOT NULL DEFAULT 0,
	`naval` INT UNSIGNED NOT NULL DEFAULT 0,
	`spies` INT UNSIGNED NOT NULL DEFAULT 0,
	`newmessage` INT UNSIGNED NOT NULL DEFAULT 0,
	`totalmessages` INT UNSIGNED NOT NULL DEFAULT 0,
	`` 	`` 	INDEX(username),
	PRIMARY KEY(id)
) Engine=InnoDb;//

DROP TABLE IF EXISTS #db#.UserSignup//
CREATE TABLE #db#.UserSignup (
	`activationkey` VARCHAR(1) NOT NULL DEFAULT "",
	`username` VARCHAR(1) NOT NULL DEFAULT "",
	`email` VARCHAR(1) NOT NULL DEFAULT "",
	`timezone` FLOAT NOT NULL DEFAULT 0.0,
	`datecreated` INT UNSIGNED NOT NULL DEFAULT 0,
	`nation` INT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(activationkey)
) Engine=InnoDb;//

DROP TABLE IF EXISTS #db#.Stats//
CREATE TABLE #db#.Stats (
	`id` INT UNSIGNED auto_increment ,
	`aerial` INT UNSIGNED NOT NULL DEFAULT 0,
	`terrestrial` INT UNSIGNED NOT NULL DEFAULT 0,
	`marine` INT UNSIGNED NOT NULL DEFAULT 0,
	`covert` INT UNSIGNED NOT NULL DEFAULT 0,
	`retaliation` INT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(id)
) Engine=InnoDb;//

DROP TABLE IF EXISTS #db#.Ranks//
CREATE TABLE #db#.Ranks (
	`id` INT UNSIGNED auto_increment ,
	`aerial` INT UNSIGNED NOT NULL DEFAULT 0,
	`terrestrial` INT UNSIGNED NOT NULL DEFAULT 0,
	`marine` INT UNSIGNED NOT NULL DEFAULT 0,
	`covert` INT UNSIGNED NOT NULL DEFAULT 0,
	`retaliation` INT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(id)
) Engine=InnoDb;//

DROP TABLE IF EXISTS #db#.Infrastructure//
CREATE TABLE #db#.Infrastructure (
	`id` INT UNSIGNED auto_increment ,
	`houses` INT UNSIGNED NOT NULL DEFAULT 500,
	`hospitals` INT UNSIGNED NOT NULL DEFAULT 0,
	`laboratories` INT UNSIGNED NOT NULL DEFAULT 0,
	`farms` INT UNSIGNED NOT NULL DEFAULT 0,
	`mines` INT UNSIGNED NOT NULL DEFAULT 0,
	`barracks` INT UNSIGNED NOT NULL DEFAULT 0,
	`airfields` INT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(id)
) Engine=InnoDb;//

DROP TABLE IF EXISTS #db#.DivisionArtillery//
CREATE TABLE #db#.DivisionArtillery (
	`userid` INT UNSIGNED NOT NULL DEFAULT 0,
	`divisionid` INT UNSIGNED NOT NULL DEFAULT 0,
	`what` INT UNSIGNED NOT NULL DEFAULT 0,
	`count` INT UNSIGNED NOT NULL DEFAULT 0,
	`damage` INT UNSIGNED NOT NULL DEFAULT 0,
	`strength` INT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(userid, divisionid)
) Engine=InnoDb;//

DROP TABLE IF EXISTS #db#.Division//
CREATE TABLE #db#.Division (
	`id` INT UNSIGNED auto_increment ,
	`userid` INT UNSIGNED NOT NULL DEFAULT 0,
	`active` INT UNSIGNED NOT NULL DEFAULT 0,
	`name` ,
	INDEX(userid),
	PRIMARY KEY(id)
) Engine=InnoDb;//

DROP TABLE IF EXISTS #db#.BuyQueue//
CREATE TABLE #db#.BuyQueue (
	`id` INT UNSIGNED auto_increment ,
	`userid` INT UNSIGNED NOT NULL DEFAULT 0,
	`what` INT UNSIGNED NOT NULL DEFAULT 0,
	`ticks` INT UNSIGNED NOT NULL DEFAULT 0,
	`quantity` INT UNSIGNED NOT NULL DEFAULT 0,
	`civilians` INT UNSIGNED NOT NULL DEFAULT 0,
	INDEX(userid),
	PRIMARY KEY(id)
) Engine=InnoDb;//

DROP TABLE IF EXISTS #db#.Attack//
CREATE TABLE #db#.Attack (
	`` 